version: '2.0'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=Tech
      - MYSQL_USER=newuser
      - MYSQL_PASSWORD=password
    ports:
      - 3304:3306
    volumes:
      - /data/mysql
  spring-boot-jpa:
    image: divyanshi5/techpublishing_1:latest
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 10001:10001
    volumes:
      - /data/spring-boot-jpa
    command: java -jar ./target/TechPublishing-0.0.1-SNAPSHOT.jar
